# =============================================================================
# 01_io.R — Lectura de los ficheros SCADA originales
# -----------------------------------------------------------------------------
# Responsable: María
# Principios:
#   * Los ficheros de data/raw NUNCA se modifican (solo lectura).
#   * El esquema de columnas se define UNA vez (scada_schema) y se usa para
#     renombrar, documentar (docs/data_dictionary.md) y validar.
#   * Las descripciones proceden literalmente de data_description.txt;
#     lo que el diccionario no documenta se marca como "No documentado".
# =============================================================================

#' Esquema de las 39 columnas según data_description.txt
#'
#' @return tibble con: letra de columna, nombre original, nombre limpio,
#'   descripción literal (inglés), unidad, tipo y grupo analítico preliminar.
scada_schema <- function() {
  nd <- "No documentado"
  tibble::tribble(
    ~col, ~original, ~name, ~description, ~unit, ~type, ~group,
    "A", "Log Time", "log_time_raw", "Local time YYYY:MM:DD:HH:MM:SS.SSS", "fecha-hora local", "tiempo", "tiempo",
    "B", "SN#", "serial_number", "Serial number of the SWT. Value = 107605", "--", "identificador", "constante documentada",
    "C", "Software rev", "software_rev", "The inverter firmware version . Value = 202", "--", "identificador", "constante documentada",
    "D", "opversion", "op_version", "The software version. Value = 300", "--", "identificador", "constante documentada",
    "E", "Inv Time", "inv_time_raw", "Decimal Timestamp by the inverter (GMT)", "s (marca decimal)", "tiempo", "tiempo",
    "F", "watt-hours", "energy_wh_cum", "Accumulated energy production (Wh)", "Wh", "contador acumulado", "salida eléctrica",
    "G", "Voltage In", "voltage_in_v", "Voltage generated by the rotor (V)", "V", "continua", "generador/rotor",
    "H", "Voltage DC Bus", "voltage_dc_bus_v", "Voltage dc bus in the inverter (V)", "V", "continua", "inversor",
    "I", "Voltage L1", "voltage_l1_v", "Grid voltage, phase L1 (V)", "V", "continua", "red eléctrica",
    "J", "Voltage L2", "voltage_l2_v", "Grid voltage, phase L2 (V)", "V", "continua", "red eléctrica",
    "K", "voltage rise", "voltage_rise_v", "Common voltage rise (V)", "V", "continua", "red eléctrica",
    "L", "min v from rpm", "min_v_from_rpm_v", "Minimum voltage for the correspondent RPM (V)", "V", "continua", "generador/rotor",
    "M", "Current out", "current_out_a", "Current ac (A)", "A", "continua", "salida eléctrica",
    "N", "Power out", "power_out_w", "Power output of the inverter (W)", "W", "continua", "salida eléctrica",
    "O", "Power reg", "power_reg_w", "Power from generator (W)", "W", "continua", "salida eléctrica",
    "P", "Power max", "power_max_w", "Inverter maximum power production (W)", "W", "continua", "inversor",
    "Q", "Line Frequency", "line_freq_hz", "Frequency at the grid (Hz)", "Hz", "continua", "red eléctrica",
    "R", "Inverter Frequency", "inverter_freq_hz", "Frequency at the inverter (Hz)", "Hz", "continua", "inversor",
    "S", "Line Resistance", "line_resistance_ohm", "Line impedance (Ohm)", "Ohm", "continua", "red eléctrica",
    "T", "RPM", "rpm", "Blade Rotations per minute", "rpm", "continua", "generador/rotor",
    "U", "Windspeed (ref)", "windspeed_ref_ms", "Integer value of windspeed from RPM (m/s)", "m/s", "entera (derivada de RPM)", "generador/rotor",
    "V", "TargetTSR", "target_tsr", "Assigned tip speed ratio", nd, "continua", "consigna de control",
    "W", "Ramp RPM", "ramp_rpm", "Assigned rotational speed", nd, "continua", "consigna de control",
    "X", "Boost pulswidth", "boost_pulsewidth", "Pulse modulation at the inverter", nd, "continua", "inversor",
    "Y", "Max BPW", "max_bpw", "Maximum pulse modulation at the inverter", nd, "continua", "inversor",
    "Z", "current amplitude", "current_amplitude", "Integer number proportional of current output", "-- (entero)", "entera", "salida eléctrica",
    "AA", "T1", "temp_heatsink1_c", "Temperature at Heatsink T1 (Celsius)", "ºC", "continua", "temperatura",
    "AB", "T2", "temp_heatsink2_c", "Temperature at Heatsink T2 (Celsius)", "ºC", "continua", "temperatura",
    "AC", "T3", "temp_nacelle_c", "Temperature at the nacelle (Celsius)", "ºC", "continua", "temperatura",
    "AD", "Event count", "event_count_cum", "Cumulative count of events", "recuento", "contador acumulado", "eventos/estado",
    "AE", "Last event code", "last_event_code", "Code of the last event", "código", "código (nominal)", "eventos/estado",
    "AF", "Event status", "event_status", "Code status of the current event", "código", "código (nominal)", "eventos/estado",
    "AG", "Event value", "event_value", "Code value of the current event", "código", "código (nominal)", "eventos/estado",
    "AH", "Turbine status", "turbine_status", "Current status code of turbine", "código", "código (nominal)", "eventos/estado",
    "AI", "Grid status", "grid_status", "Code status of the connected grid", "código", "código (nominal)", "eventos/estado",
    "AJ", "System status", "system_status", "Code status of the system", "código", "código (nominal)", "eventos/estado",
    "AK", "Slave Status", "slave_status", "Code status of the system", "código", "código (nominal)", "eventos/estado",
    "AL", "Access Status", "access_status", "Access level (signal strength)", nd, "código (nominal)", "eventos/estado",
    "AM", "Timer", "timer", "Timer countdown to zero after some event", nd, "continua", "eventos/estado"
  )
}

#' Valores constantes que el propio diccionario documenta
documented_constants <- function() {
  c(serial_number = 107605, software_rev = 202, op_version = 300)
}

#' Columnas de código de estado (nominales aunque se almacenen como número)
status_columns <- function() {
  s <- scada_schema()
  s$name[s$type == "código (nominal)"]
}

# -----------------------------------------------------------------------------
# Detección de ficheros
# -----------------------------------------------------------------------------

#' Detecta los ficheros anuales en data/raw
#'
#' @param raw_dir Directorio con los CSV originales.
#' @param pattern Expresión regular con el año como primer grupo.
#' @return tibble con file, path, year (del nombre) y size_mb.
list_raw_files <- function(raw_dir = project_path("raw_dir"),
                           pattern = load_config()$raw_format$file_pattern) {
  files <- sort(list.files(raw_dir, pattern = pattern, full.names = TRUE))
  if (length(files) == 0) {
    stop("No hay ficheros 'data_swt_iee_usp_YYYY.csv' en ", raw_dir,
         ".\nConsulta data/README.md para descargarlos.", call. = FALSE)
  }
  tibble::tibble(
    file = basename(files),
    path = files,
    year = as.integer(sub(pattern, "\\1", basename(files))),
    size_mb = round(file.size(files) / 1024^2, 2)
  )
}

#' Manifiesto de los ficheros originales (tamaño y huella MD5)
#'
#' Permite comprobar que data/raw no se modifica accidentalmente.
raw_manifest <- function(files) {
  dplyr::mutate(files[c("file", "year", "size_mb")],
                md5 = unname(tools::md5sum(files$path)))
}

#' Cabecera de un fichero con espacios exteriores eliminados
#'
#' Nota: en 2017 la columna T1 aparece como " T1" (con espacio inicial).
read_raw_header <- function(path, delim = ";") {
  header <- readLines(path, n = 1, warn = FALSE)
  trimws(strsplit(header, delim, fixed = TRUE)[[1]])
}

# -----------------------------------------------------------------------------
# Validación del esquema
# -----------------------------------------------------------------------------

#' Compara la cabecera de cada fichero con el esquema documentado
#'
#' @return tibble (una fila por fichero) con nº de columnas, columnas que
#'   faltan, columnas no documentadas, orden y compatibilidad.
validate_schema <- function(files, schema = scada_schema()) {
  rows <- lapply(seq_len(nrow(files)), function(i) {
    header <- read_raw_header(files$path[i])
    raw_header <- strsplit(readLines(files$path[i], n = 1, warn = FALSE),
                           ";", fixed = TRUE)[[1]]
    missing <- setdiff(schema$original, header)
    extra <- setdiff(header, schema$original)
    tibble::tibble(
      file = files$file[i],
      n_columns = length(header),
      missing_columns = paste(missing, collapse = ", "),
      extra_columns = paste(extra, collapse = ", "),
      same_order = identical(header, schema$original),
      names_with_spaces = paste(raw_header[raw_header != trimws(raw_header)],
                                collapse = ", "),
      compatible = length(missing) == 0 && length(extra) == 0
    )
  })
  dplyr::bind_rows(rows)
}

#' Detiene la ejecución si algún fichero no es compatible con el esquema
assert_schema_compatible <- function(schema_check) {
  bad <- schema_check$file[!schema_check$compatible]
  if (length(bad) > 0) {
    stop("Estructura de columnas incompatible en: ",
         paste(bad, collapse = ", "),
         ". Revisa la salida de validate_schema().", call. = FALSE)
  }
  invisible(TRUE)
}

# -----------------------------------------------------------------------------
# Lectura
# -----------------------------------------------------------------------------

#' Lee un fichero anual con nombres limpios y tipos explícitos
#'
#' `Log Time` e `Inv Time` se leen como texto (se parsean en 02_cleaning.R);
#' el resto como numérico con punto decimal, según el diccionario. Los valores
#' no numéricos se convierten en NA y quedan registrados en el atributo
#' "parse_problems" (no se pierden silenciosamente).
#'
#' @param path Ruta al CSV original.
#' @param schema Esquema (scada_schema()).
#' @return tibble con columnas limpias + source_file.
load_year_data <- function(path, schema = scada_schema()) {
  header <- read_raw_header(path)
  name_map <- stats::setNames(schema$name, schema$original)
  if (!all(header %in% names(name_map))) {
    stop("Columnas no documentadas en ", basename(path), ": ",
         paste(setdiff(header, names(name_map)), collapse = ", "),
         call. = FALSE)
  }
  clean_names <- unname(name_map[header])
  col_types <- readr::cols(.default = readr::col_double(),
                           log_time_raw = readr::col_character(),
                           inv_time_raw = readr::col_character())
  data <- readr::read_delim(
    path, delim = ";", skip = 1, col_names = clean_names,
    col_types = col_types, locale = readr::locale(decimal_mark = "."),
    trim_ws = TRUE, na = c("", "NA"), progress = FALSE
  )
  problems <- readr::problems(data)
  data <- dplyr::mutate(data, source_file = basename(path), .before = 1)
  attr(data, "parse_problems") <- dplyr::mutate(problems,
                                                file = basename(path))
  data
}

#' Lee y combina todos los años
#'
#' Comprueba antes la compatibilidad del esquema y conserva los problemas de
#' parseo de cada fichero en el atributo "parse_problems".
#'
#' @param files Salida de list_raw_files().
#' @return tibble combinado (filas en el orden original de los ficheros).
load_all_years <- function(files = list_raw_files()) {
  assert_schema_compatible(validate_schema(files))
  pieces <- lapply(files$path, load_year_data)
  problems <- dplyr::bind_rows(lapply(pieces, attr, "parse_problems"))
  data <- dplyr::bind_rows(pieces)
  data <- dplyr::left_join(data,
                           dplyr::select(files, source_file = file,
                                         file_year = year),
                           by = "source_file")
  attr(data, "parse_problems") <- problems
  data
}
